waypoints:
  - {id: 0, x: -4.00995779037, y: -0.996777892113}
  - {id: 1, x:  4.34944057465, y: -0.553416728973}
  - {id: 2, x: 15.0812244415,  y:  0.201877117157}
  - {id: 3, x: 14.6693248749,  y:  8.143907547}
  - {id: 4, x: 17.9891986847, y:  0.419644832611}

edges:
  - {from: 0, to: 1, cost: 8.37}
  - {from: 1, to: 2, cost: 10.76}
  - {from: 2, to: 3, cost: 7.95}   
  - {from: 2, to: 4, cost: 2.92}
